<?php

namespace Database\Seeders;

use App\Models\Client;
use App\Models\Product;
use App\Models\Supplier;
use App\Models\InstrumentSet;
use Illuminate\Database\Seeder;

class SampleMasterDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $suppliers = [
            [
                'supplier_name' => 'Tremed Surgical Solution Sdn Bhd',
                'pic_name' => 'Zikri Rahman',
                'phone' => '+60-3-7887-6398',
                'email' => 'sales@tremedsurgical.com.my',
                'address' => 'No. 6-1, Block A, Zenith Corporate Park, Jalan SS 7/26, Kelana Jaya, 47301 Petaling Jaya, Selangor',
                'is_active' => true,
            ],
            [
                'supplier_name' => 'Medikraft Orthopaedic Supplies Sdn Bhd',
                'pic_name' => 'Ahmad Faizal',
                'phone' => '+60-3-5512-3456',
                'email' => 'sales@medikraft.com.my',
                'address' => 'No. 18, Jalan Anggerik Vanilla 31/93, Kota Kemuning Industrial Park, 40460 Shah Alam, Selangor',
                'is_active' => true,
            ],
            [
                'supplier_name' => 'Borneo Meditech Distribution Sdn Bhd',
                'pic_name' => 'Lim Wei Jie',
                'phone' => '+60-3-8068-2190',
                'email' => 'orders@borneomeditech.com.my',
                'address' => 'Lot 12, Jalan TPP 5/17, Taman Perindustrian Puchong, 47100 Puchong, Selangor',
                'is_active' => true,
            ],
            [
                'supplier_name' => 'Sinar Sterile Healthcare Sdn Bhd',
                'pic_name' => 'Nur Aisyah Hassan',
                'phone' => '+60-3-7845-6620',
                'email' => 'cs@sinarsterile.com.my',
                'address' => 'No. 22, Jalan U1/26, Hicom Glenmarie Industrial Park, 40150 Shah Alam, Selangor',
                'is_active' => true,
            ],
            [
                'supplier_name' => 'Penang Precision Medical Devices Sdn Bhd',
                'pic_name' => 'Tan Mei Ling',
                'phone' => '+60-4-644-9088',
                'email' => 'sales@ppmedical.com.my',
                'address' => 'Plot 88, Lorong Perindustrian Bukit Minyak 12, Kawasan Perindustrian Bukit Minyak, 14100 Simpang Ampat, Pulau Pinang',
                'is_active' => true,
            ],
            [
                'supplier_name' => 'Bayan Lepas Surgical Instruments Sdn Bhd',
                'pic_name' => 'Mohd Hafiz Ismail',
                'phone' => '+60-4-646-3177',
                'email' => 'procurement@blsurgical.com.my',
                'address' => 'No. 15, Lintang Bayan Lepas 6, Bayan Lepas Industrial Park, 11900 Bayan Lepas, Pulau Pinang',
                'is_active' => true,
            ],
            [
                'supplier_name' => 'Johor Medline Distribution Sdn Bhd',
                'pic_name' => 'Muthu Rajan',
                'phone' => '+60-7-562-4410',
                'email' => 'sales.johor@johormedline.com.my',
                'address' => 'No. 31, Jalan Perindustrian 2, Kawasan Perindustrian Senai, 81400 Senai, Johor',
                'is_active' => true,
            ],
            [
                'supplier_name' => 'KL Endoscopy & Surgical Supply Sdn Bhd',
                'pic_name' => 'Siti Farhana Abdullah',
                'phone' => '+60-3-6279-8801',
                'email' => 'admin@klendosurgical.com.my',
                'address' => 'Unit 3-12, Jalan Metro Perdana Barat 1, Taman Usahawan Kepong, 52100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur',
                'is_active' => true,
            ],
        ];

        foreach ($suppliers as $supplier) {
            Supplier::query()->firstOrCreate(['supplier_name' => $supplier['supplier_name']], $supplier);
        }

        $clients = [
            [
                'client_name' => 'Hospital Kuala Lumpur',
                'client_type' => 'hospital',
                'phone' => '+60-3-2615-5555',
                'email' => 'procurement.hkl@tretech-demo.my',
                'address' => 'Jalan Pahang, 50586 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur',
                'is_active' => true,
            ],
            [
                'client_name' => 'Hospital Selayang',
                'client_type' => 'hospital',
                'phone' => '+60-3-6126-3333',
                'email' => 'stor.perubatan.selayang@tretech-demo.my',
                'address' => 'Lebuhraya Selayang-Kepong, 68100 Batu Caves, Selangor',
                'is_active' => true,
            ],
            [
                'client_name' => 'Pusat Perubatan Universiti Malaya',
                'client_type' => 'hospital',
                'phone' => '+60-3-7949-4422',
                'email' => 'unit.perolehan.ppum@tretech-demo.my',
                'address' => 'Lembah Pantai, 59100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur',
                'is_active' => true,
            ],
            [
                'client_name' => 'Subang Jaya Medical Centre',
                'client_type' => 'hospital',
                'phone' => '+60-3-5639-1212',
                'email' => 'supplychain.sjmc@tretech-demo.my',
                'address' => 'No. 1, Jalan SS 12/1A, 47500 Subang Jaya, Selangor',
                'is_active' => true,
            ],
            [
                'client_name' => 'Pantai Hospital Penang',
                'client_type' => 'hospital',
                'phone' => '+60-4-643-3888',
                'email' => 'procurement.phpg@tretech-demo.my',
                'address' => '82, Jalan Tengah, Bayan Baru, 11900 Bayan Lepas, Pulau Pinang',
                'is_active' => true,
            ],
            [
                'client_name' => 'Hospital Sultanah Aminah Johor Bahru',
                'client_type' => 'hospital',
                'phone' => '+60-7-225-7000',
                'email' => 'bekalan.hsa@tretech-demo.my',
                'address' => 'Jalan Persiaran Abu Bakar Sultan, 80100 Johor Bahru, Johor',
                'is_active' => true,
            ],
            [
                'client_name' => 'KPJ Johor Specialist Hospital',
                'client_type' => 'hospital',
                'phone' => '+60-7-225-3000',
                'email' => 'materials.kpjjohor@tretech-demo.my',
                'address' => '39-B, Jalan Abdul Samad, Kolam Ayer, 80100 Johor Bahru, Johor',
                'is_active' => true,
            ],
            [
                'client_name' => 'Klinik Kesihatan Kelana Jaya',
                'client_type' => 'clinic',
                'phone' => '+60-3-7806-1022',
                'email' => 'kk.kelanajaya@tretech-demo.my',
                'address' => 'Jalan SS 6/3, Kelana Jaya, 47301 Petaling Jaya, Selangor',
                'is_active' => true,
            ],
            [
                'client_name' => 'Klinik Pakar Ortopedik Damansara',
                'client_type' => 'clinic',
                'phone' => '+60-3-7728-9011',
                'email' => 'admin.ortho.damansara@tretech-demo.my',
                'address' => 'No. 18-1, Jalan PJU 5/20, The Strand, Kota Damansara, 47810 Petaling Jaya, Selangor',
                'is_active' => true,
            ],
            [
                'client_name' => 'Klinik Perubatan Bayan Baru',
                'client_type' => 'clinic',
                'phone' => '+60-4-646-2188',
                'email' => 'admin.klinikbayanbaru@tretech-demo.my',
                'address' => 'No. 34, Medan Kampung Relau, Bayan Baru, 11900 Bayan Lepas, Pulau Pinang',
                'is_active' => true,
            ],
        ];

        foreach ($clients as $client) {
            Client::query()->firstOrCreate(['client_name' => $client['client_name'], 'client_type' => $client['client_type']], $client);
        }

        $products = [
            // New products
            [
                'ref_num' => '115012300',
                'product_name' => 'Hamstring Tendon Stripper, Ø7mm, Close End',
                'product_type' => 'instrument',
                'category' => 'Orthopedic',
                'uom' => 'pcs',
                'requires_expiry' => false,
                'requires_lot' => false,
                'is_active' => true,
            ],
            [
                'ref_num' => '115011400',
                'product_name' => 'Graft Sizing Block',
                'product_type' => 'instrument',
                'category' => 'Orthopedic',
                'uom' => 'pcs',
                'requires_expiry' => false,
                'requires_lot' => false,
                'is_active' => true,
            ],
            [
                'ref_num' => '115011500',
                'product_name' => 'Tibial ACL Drill Guide, Pin Tip',
                'product_type' => 'instrument',
                'category' => 'Orthopedic',
                'uom' => 'pcs',
                'requires_expiry' => false,
                'requires_lot' => false,
                'is_active' => true,
            ],
            [
                'ref_num' => '115010300',
                'product_name' => 'Tibial ACL Drill Guide, Footprint',
                'product_type' => 'instrument',
                'category' => 'Orthopedic',
                'uom' => 'pcs',
                'requires_expiry' => false,
                'requires_lot' => false,
                'is_active' => true,
            ],
            [
                'ref_num' => '115011600',
                'product_name' => 'Side-Release Handle',
                'product_type' => 'instrument',
                'category' => 'Orthopedic',
                'uom' => 'pcs',
                'requires_expiry' => false,
                'requires_lot' => false,
                'is_active' => true,
            ],
            [
                'ref_num' => '115010200',
                'product_name' => 'Femoral Guide Drill Sleeve, Ø2.4mm',
                'product_type' => 'instrument',
                'category' => 'Orthopedic',
                'uom' => 'pcs',
                'requires_expiry' => false,
                'requires_lot' => false,
                'is_active' => true,
            ],
            [
                'ref_num' => '115012900',
                'product_name' => 'Drill Tip Guide Pin, Ø2.4mm',
                'product_type' => 'instrument',
                'category' => 'Orthopedic',
                'uom' => 'pcs',
                'requires_expiry' => false,
                'requires_lot' => false,
                'is_active' => true,
            ],
            [
                'ref_num' => '115013400',
                'product_name' => 'Tibial Tunnel Passing Femoral Drill Guide, Ø5mm',
                'product_type' => 'instrument',
                'category' => 'Orthopedic',
                'uom' => 'pcs',
                'requires_expiry' => false,
                'requires_lot' => false,
                'is_active' => true,
            ],
            [
                'ref_num' => '115011800',
                'product_name' => 'Tibial Tunnel Passing Femoral Drill Guide, Ø6mm',
                'product_type' => 'instrument',
                'category' => 'Orthopedic',
                'uom' => 'pcs',
                'requires_expiry' => false,
                'requires_lot' => false,
                'is_active' => true,
            ],
            [
                'ref_num' => '115013500',
                'product_name' => 'Tibial Tunnel Passing Femoral Drill Guide, Ø7mm',
                'product_type' => 'instrument',
                'category' => 'Orthopedic',
                'uom' => 'pcs',
                'requires_expiry' => false,
                'requires_lot' => false,
                'is_active' => true,
            ],
            [
                'ref_num' => '115015700',
                'product_name' => 'Femoral ACL Drill Guide, Footprint, Left',
                'product_type' => 'instrument',
                'category' => 'Orthopedic',
                'uom' => 'pcs',
                'requires_expiry' => false,
                'requires_lot' => false,
                'is_active' => true,
            ],
            [
                'ref_num' => '115015800',
                'product_name' => 'Femoral ACL Drill Guide, Footprint, Right',
                'product_type' => 'instrument',
                'category' => 'Orthopedic',
                'uom' => 'pcs',
                'requires_expiry' => false,
                'requires_lot' => false,
                'is_active' => true,
            ],
            [
                'ref_num' => '115012400',
                'product_name' => 'Ratcheting Drill Sleeve for FlipCutter, 7mm Step, Ø3.5mm',
                'product_type' => 'instrument',
                'category' => 'Orthopedic',
                'uom' => 'pcs',
                'requires_expiry' => false,
                'requires_lot' => false,
                'is_active' => true,
            ],
            [
                'ref_num' => '115014800',
                'product_name' => 'FlipCutter Reamer, Ø6mm',
                'product_type' => 'instrument',
                'category' => 'Orthopedic',
                'uom' => 'pcs',
                'requires_expiry' => false,
                'requires_lot' => false,
                'is_active' => true,
            ],
            [
                'ref_num' => '115014900',
                'product_name' => 'FlipCutter Reamer, Ø7mm',
                'product_type' => 'instrument',
                'category' => 'Orthopedic',
                'uom' => 'pcs',
                'requires_expiry' => false,
                'requires_lot' => false,
                'is_active' => true,
            ]
        ];

        foreach ($products as $product) {
            Product::query()->firstOrCreate(['ref_num' => $product['ref_num']], $product);
        }

        $instrumentSets = [
            [
                'set_code' => 'SET-ORTHO-ACL-01',
                'set_name' => 'ACL Reconstruction Instrument Set',
                'description' => 'Used for arthroscopic anterior cruciate ligament reconstruction, tunnel preparation, graft sizing, and fixation support.',
                'is_active' => true,
                'instruments' => [
                    [
                        'code' => 'INST-ACL-001',
                        'name' => 'Hamstring Tendon Stripper, Closed End, 7mm',
                        'quantity' => 1,
                        'sort_order' => 1,
                        'remarks' => 'For semitendinosus/gracilis tendon harvesting',
                    ],
                    [
                        'code' => 'INST-ACL-002',
                        'name' => 'Graft Sizing Block',
                        'quantity' => 1,
                        'sort_order' => 2,
                        'remarks' => 'Sizing range 6mm to 12mm',
                    ],
                    [
                        'code' => 'INST-ACL-003',
                        'name' => 'Tibial ACL Drill Guide, Pin Tip',
                        'quantity' => 1,
                        'sort_order' => 3,
                        'remarks' => 'For tibial tunnel targeting',
                    ],
                    [
                        'code' => 'INST-ACL-004',
                        'name' => 'Tibial ACL Drill Guide, Footprint',
                        'quantity' => 1,
                        'sort_order' => 4,
                        'remarks' => 'Footprint-style guide',
                    ],
                    [
                        'code' => 'INST-ACL-005',
                        'name' => 'Femoral ACL Drill Guide, Left',
                        'quantity' => 1,
                        'sort_order' => 5,
                        'remarks' => 'Left knee orientation',
                    ],
                    [
                        'code' => 'INST-ACL-006',
                        'name' => 'Femoral ACL Drill Guide, Right',
                        'quantity' => 1,
                        'sort_order' => 6,
                        'remarks' => 'Right knee orientation',
                    ],
                    [
                        'code' => 'INST-ACL-007',
                        'name' => 'Ratcheting Drill Sleeve for FlipCutter',
                        'quantity' => 1,
                        'sort_order' => 7,
                        'remarks' => '7mm step, 3.5mm sleeve',
                    ],
                    [
                        'code' => 'INST-ACL-008',
                        'name' => 'FlipCutter Reamer, 6mm',
                        'quantity' => 1,
                        'sort_order' => 8,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-ACL-009',
                        'name' => 'FlipCutter Reamer, 7mm',
                        'quantity' => 1,
                        'sort_order' => 9,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-ACL-010',
                        'name' => 'FlipCutter Reamer, 8mm',
                        'quantity' => 1,
                        'sort_order' => 10,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-ACL-011',
                        'name' => 'Guide Wire, 1.1mm x 360mm',
                        'quantity' => 2,
                        'sort_order' => 11,
                        'remarks' => 'Reusable guide wire',
                    ],
                    [
                        'code' => null,
                        'name' => 'Graft Preparation Board',
                        'quantity' => 1,
                        'sort_order' => 12,
                        'remarks' => 'For graft preparation table',
                    ],
                ],
            ],
            [
                'set_code' => 'SET-ORTHO-BONE-02',
                'set_name' => 'Basic Bone Plating Instrument Set',
                'description' => 'Used for open reduction and internal fixation of simple fractures requiring plates and screws.',
                'is_active' => true,
                'instruments' => [
                    [
                        'code' => 'INST-BONE-001',
                        'name' => 'Bone Holding Forceps, Large',
                        'quantity' => 2,
                        'sort_order' => 1,
                        'remarks' => 'Serrated jaw',
                    ],
                    [
                        'code' => 'INST-BONE-002',
                        'name' => 'Reduction Forceps with Points',
                        'quantity' => 2,
                        'sort_order' => 2,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-BONE-003',
                        'name' => 'Periosteal Elevator, 15mm',
                        'quantity' => 1,
                        'sort_order' => 3,
                        'remarks' => 'For soft tissue elevation',
                    ],
                    [
                        'code' => 'INST-BONE-004',
                        'name' => 'Hohmann Retractor, Small',
                        'quantity' => 2,
                        'sort_order' => 4,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-BONE-005',
                        'name' => 'Hohmann Retractor, Medium',
                        'quantity' => 2,
                        'sort_order' => 5,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-BONE-006',
                        'name' => 'Drill Guide, 2.5mm',
                        'quantity' => 1,
                        'sort_order' => 6,
                        'remarks' => 'For 3.5mm cortical screws',
                    ],
                    [
                        'code' => 'INST-BONE-007',
                        'name' => 'Twist Drill Bit, 2.5mm',
                        'quantity' => 2,
                        'sort_order' => 7,
                        'remarks' => 'Check sharpness before use',
                    ],
                    [
                        'code' => 'INST-BONE-008',
                        'name' => 'Depth Gauge, 60mm',
                        'quantity' => 1,
                        'sort_order' => 8,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-BONE-009',
                        'name' => 'Tap for 3.5mm Cortical Screw',
                        'quantity' => 1,
                        'sort_order' => 9,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-BONE-010',
                        'name' => 'Hex Screwdriver, 2.5mm',
                        'quantity' => 2,
                        'sort_order' => 10,
                        'remarks' => 'For small fragment system',
                    ],
                    [
                        'code' => null,
                        'name' => 'Plate Bending Iron Pair',
                        'quantity' => 1,
                        'sort_order' => 11,
                        'remarks' => 'Pair counted as one set',
                    ],
                ],
            ],
            [
                'set_code' => 'SET-GENSURG-MINOR-01',
                'set_name' => 'Minor Surgery Tray',
                'description' => 'Used for minor procedures such as wound exploration, incision and drainage, biopsy, and simple soft tissue repair.',
                'is_active' => true,
                'instruments' => [
                    [
                        'code' => 'INST-MIN-001',
                        'name' => 'Scalpel Handle No. 3',
                        'quantity' => 1,
                        'sort_order' => 1,
                        'remarks' => 'For blades No. 10, 11, 15',
                    ],
                    [
                        'code' => 'INST-MIN-002',
                        'name' => 'Mayo Scissors, Straight, 15cm',
                        'quantity' => 1,
                        'sort_order' => 2,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-MIN-003',
                        'name' => 'Metzenbaum Scissors, Curved, 18cm',
                        'quantity' => 1,
                        'sort_order' => 3,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-MIN-004',
                        'name' => 'Adson Tissue Forceps, 1x2 Teeth',
                        'quantity' => 1,
                        'sort_order' => 4,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-MIN-005',
                        'name' => 'Adson Dressing Forceps, Serrated',
                        'quantity' => 1,
                        'sort_order' => 5,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-MIN-006',
                        'name' => 'Mosquito Artery Forceps, Curved',
                        'quantity' => 4,
                        'sort_order' => 6,
                        'remarks' => 'Small hemostat',
                    ],
                    [
                        'code' => 'INST-MIN-007',
                        'name' => 'Needle Holder, Mayo-Hegar, 15cm',
                        'quantity' => 1,
                        'sort_order' => 7,
                        'remarks' => null,
                    ],
                    [
                        'code' => null,
                        'name' => 'Sponge Holding Forceps',
                        'quantity' => 1,
                        'sort_order' => 8,
                        'remarks' => null,
                    ],
                    [
                        'code' => null,
                        'name' => 'Small Gallipot',
                        'quantity' => 2,
                        'sort_order' => 9,
                        'remarks' => 'For antiseptic or saline',
                    ],
                ],
            ],
            [
                'set_code' => 'SET-GENSURG-LAP-02',
                'set_name' => 'Laparotomy Instrument Set',
                'description' => 'Used for open abdominal procedures, bowel surgery, exploratory laparotomy, and major general surgery cases.',
                'is_active' => true,
                'instruments' => [
                    [
                        'code' => 'INST-LAP-001',
                        'name' => 'Scalpel Handle No. 4',
                        'quantity' => 2,
                        'sort_order' => 1,
                        'remarks' => 'For larger abdominal blades',
                    ],
                    [
                        'code' => 'INST-LAP-002',
                        'name' => 'Mayo Scissors, Curved, 17cm',
                        'quantity' => 2,
                        'sort_order' => 2,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-LAP-003',
                        'name' => 'Metzenbaum Scissors, Curved, 23cm',
                        'quantity' => 2,
                        'sort_order' => 3,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-LAP-004',
                        'name' => 'Kelly Artery Forceps, Curved',
                        'quantity' => 6,
                        'sort_order' => 4,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-LAP-005',
                        'name' => 'Kocher Forceps, Straight',
                        'quantity' => 4,
                        'sort_order' => 5,
                        'remarks' => 'Toothed hemostat',
                    ],
                    [
                        'code' => 'INST-LAP-006',
                        'name' => 'Babcock Tissue Forceps',
                        'quantity' => 4,
                        'sort_order' => 6,
                        'remarks' => 'For bowel handling',
                    ],
                    [
                        'code' => 'INST-LAP-007',
                        'name' => 'Allis Tissue Forceps',
                        'quantity' => 4,
                        'sort_order' => 7,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-LAP-008',
                        'name' => 'Deaver Retractor, Medium',
                        'quantity' => 2,
                        'sort_order' => 8,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-LAP-009',
                        'name' => 'Richardson Retractor',
                        'quantity' => 2,
                        'sort_order' => 9,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-LAP-010',
                        'name' => 'Mayo-Hegar Needle Holder, 20cm',
                        'quantity' => 2,
                        'sort_order' => 10,
                        'remarks' => null,
                    ],
                    [
                        'code' => null,
                        'name' => 'Sponge Holding Forceps',
                        'quantity' => 4,
                        'sort_order' => 11,
                        'remarks' => null,
                    ],
                    [
                        'code' => null,
                        'name' => 'Instrument Bowl, Stainless Steel',
                        'quantity' => 2,
                        'sort_order' => 12,
                        'remarks' => null,
                    ],
                ],
            ],
            [
                'set_code' => 'SET-CARDIO-CABG-01',
                'set_name' => 'Cardiothoracic CABG Instrument Set',
                'description' => 'Used for coronary artery bypass grafting and open cardiac procedures requiring fine vascular and thoracic instruments.',
                'is_active' => true,
                'instruments' => [
                    [
                        'code' => 'INST-CABG-001',
                        'name' => 'Debakey Tissue Forceps, 20cm',
                        'quantity' => 2,
                        'sort_order' => 1,
                        'remarks' => 'Atraumatic vascular pattern',
                    ],
                    [
                        'code' => 'INST-CABG-002',
                        'name' => 'Debakey Tissue Forceps, 24cm',
                        'quantity' => 2,
                        'sort_order' => 2,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-CABG-003',
                        'name' => 'Potts-Smith Scissors, 45 Degree',
                        'quantity' => 1,
                        'sort_order' => 3,
                        'remarks' => 'Fine vascular scissors',
                    ],
                    [
                        'code' => 'INST-CABG-004',
                        'name' => 'Potts-Smith Scissors, 60 Degree',
                        'quantity' => 1,
                        'sort_order' => 4,
                        'remarks' => 'Fine vascular scissors',
                    ],
                    [
                        'code' => 'INST-CABG-005',
                        'name' => 'Castroviejo Needle Holder, Curved',
                        'quantity' => 2,
                        'sort_order' => 5,
                        'remarks' => 'For fine vascular sutures',
                    ],
                    [
                        'code' => 'INST-CABG-006',
                        'name' => 'Bulldog Vascular Clamp, Small',
                        'quantity' => 4,
                        'sort_order' => 6,
                        'remarks' => 'Atraumatic clamp',
                    ],
                    [
                        'code' => 'INST-CABG-007',
                        'name' => 'Satinsky Vascular Clamp',
                        'quantity' => 2,
                        'sort_order' => 7,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-CABG-008',
                        'name' => 'Sternal Retractor',
                        'quantity' => 1,
                        'sort_order' => 8,
                        'remarks' => 'Adult size',
                    ],
                    [
                        'code' => 'INST-CABG-009',
                        'name' => 'Finochietto Rib Spreader',
                        'quantity' => 1,
                        'sort_order' => 9,
                        'remarks' => null,
                    ],
                    [
                        'code' => null,
                        'name' => 'Vascular Dilator Set',
                        'quantity' => 1,
                        'sort_order' => 10,
                        'remarks' => 'Assorted small sizes',
                    ],
                ],
            ],
            [
                'set_code' => 'SET-THORACIC-CHEST-01',
                'set_name' => 'Thoracic Chest Procedure Set',
                'description' => 'Used for thoracotomy support, chest drain insertion, and pleural access procedures.',
                'is_active' => true,
                'instruments' => [
                    [
                        'code' => 'INST-THOR-001',
                        'name' => 'Scalpel Handle No. 4',
                        'quantity' => 1,
                        'sort_order' => 1,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-THOR-002',
                        'name' => 'Mayo Scissors, Curved, 17cm',
                        'quantity' => 1,
                        'sort_order' => 2,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-THOR-003',
                        'name' => 'Kelly Artery Forceps, Curved',
                        'quantity' => 4,
                        'sort_order' => 3,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-THOR-004',
                        'name' => 'Rochester-Pean Forceps, Curved',
                        'quantity' => 2,
                        'sort_order' => 4,
                        'remarks' => 'Heavy hemostat',
                    ],
                    [
                        'code' => 'INST-THOR-005',
                        'name' => 'Tonsil Forceps, Curved',
                        'quantity' => 2,
                        'sort_order' => 5,
                        'remarks' => 'Useful for tunneling chest tube tract',
                    ],
                    [
                        'code' => 'INST-THOR-006',
                        'name' => 'Finochietto Rib Spreader, Small',
                        'quantity' => 1,
                        'sort_order' => 6,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-THOR-007',
                        'name' => 'Sponge Holding Forceps',
                        'quantity' => 2,
                        'sort_order' => 7,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-THOR-008',
                        'name' => 'Mayo-Hegar Needle Holder, 18cm',
                        'quantity' => 1,
                        'sort_order' => 8,
                        'remarks' => null,
                    ],
                    [
                        'code' => null,
                        'name' => 'Towel Clip, Backhaus',
                        'quantity' => 4,
                        'sort_order' => 9,
                        'remarks' => null,
                    ],
                ],
            ],
            [
                'set_code' => 'SET-NEURO-CRANI-01',
                'set_name' => 'Craniotomy Instrument Set',
                'description' => 'Used for cranial bone flap creation, dural exposure, and neurosurgical access procedures.',
                'is_active' => true,
                'instruments' => [
                    [
                        'code' => 'INST-CRAN-001',
                        'name' => 'Scalpel Handle No. 3',
                        'quantity' => 1,
                        'sort_order' => 1,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-CRAN-002',
                        'name' => 'Raney Clip Applier',
                        'quantity' => 1,
                        'sort_order' => 2,
                        'remarks' => 'For scalp hemostasis',
                    ],
                    [
                        'code' => 'INST-CRAN-003',
                        'name' => 'Periosteal Elevator, Straight',
                        'quantity' => 2,
                        'sort_order' => 3,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-CRAN-004',
                        'name' => 'Hudson Brace with Burr Attachments',
                        'quantity' => 1,
                        'sort_order' => 4,
                        'remarks' => 'Manual cranial burr system',
                    ],
                    [
                        'code' => 'INST-CRAN-005',
                        'name' => 'Adson Rongeur',
                        'quantity' => 1,
                        'sort_order' => 5,
                        'remarks' => 'For cranial bone edge work',
                    ],
                    [
                        'code' => 'INST-CRAN-006',
                        'name' => 'Kerrison Rongeur, 2mm',
                        'quantity' => 1,
                        'sort_order' => 6,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-CRAN-007',
                        'name' => 'Dural Hook',
                        'quantity' => 2,
                        'sort_order' => 7,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-CRAN-008',
                        'name' => 'Bayonet Forceps, Serrated',
                        'quantity' => 2,
                        'sort_order' => 8,
                        'remarks' => 'Neurosurgical pattern',
                    ],
                    [
                        'code' => 'INST-CRAN-009',
                        'name' => 'Yasargil Micro Scissors',
                        'quantity' => 1,
                        'sort_order' => 9,
                        'remarks' => 'Fine dissection',
                    ],
                    [
                        'code' => 'INST-CRAN-010',
                        'name' => 'Leyla Brain Retractor Arm',
                        'quantity' => 1,
                        'sort_order' => 10,
                        'remarks' => 'Retractor support arm',
                    ],
                    [
                        'code' => null,
                        'name' => 'Brain Spatula, Malleable',
                        'quantity' => 2,
                        'sort_order' => 11,
                        'remarks' => 'Assorted widths',
                    ],
                ],
            ],
            [
                'set_code' => 'SET-NEURO-SPINE-02',
                'set_name' => 'Spine Decompression Instrument Set',
                'description' => 'Used for lumbar decompression, laminectomy, and posterior spinal exposure procedures.',
                'is_active' => true,
                'instruments' => [
                    [
                        'code' => 'INST-SPINE-001',
                        'name' => 'Cobb Elevator, 25mm',
                        'quantity' => 1,
                        'sort_order' => 1,
                        'remarks' => 'For paraspinal muscle elevation',
                    ],
                    [
                        'code' => 'INST-SPINE-002',
                        'name' => 'Leksell Rongeur',
                        'quantity' => 1,
                        'sort_order' => 2,
                        'remarks' => 'Bone removal',
                    ],
                    [
                        'code' => 'INST-SPINE-003',
                        'name' => 'Kerrison Rongeur, 1mm',
                        'quantity' => 1,
                        'sort_order' => 3,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-SPINE-004',
                        'name' => 'Kerrison Rongeur, 2mm',
                        'quantity' => 1,
                        'sort_order' => 4,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-SPINE-005',
                        'name' => 'Kerrison Rongeur, 3mm',
                        'quantity' => 1,
                        'sort_order' => 5,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-SPINE-006',
                        'name' => 'Penfield Dissector No. 4',
                        'quantity' => 1,
                        'sort_order' => 6,
                        'remarks' => 'Neural tissue dissection',
                    ],
                    [
                        'code' => 'INST-SPINE-007',
                        'name' => 'Woodson Elevator',
                        'quantity' => 1,
                        'sort_order' => 7,
                        'remarks' => 'Nerve root exploration',
                    ],
                    [
                        'code' => 'INST-SPINE-008',
                        'name' => 'Love Nerve Root Retractor',
                        'quantity' => 1,
                        'sort_order' => 8,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-SPINE-009',
                        'name' => 'Pituitary Rongeur, Straight',
                        'quantity' => 1,
                        'sort_order' => 9,
                        'remarks' => 'Disc material removal',
                    ],
                    [
                        'code' => null,
                        'name' => 'Taylor Spinal Retractor',
                        'quantity' => 2,
                        'sort_order' => 10,
                        'remarks' => null,
                    ],
                ],
            ],
            [
                'set_code' => 'SET-ENT-TONSIL-01',
                'set_name' => 'ENT Tonsillectomy and Adenoidectomy Set',
                'description' => 'Used for tonsillectomy, adenoidectomy, and common ENT soft tissue procedures.',
                'is_active' => true,
                'instruments' => [
                    [
                        'code' => 'INST-ENT-001',
                        'name' => 'Boyle-Davis Mouth Gag',
                        'quantity' => 1,
                        'sort_order' => 1,
                        'remarks' => 'With tongue blades',
                    ],
                    [
                        'code' => 'INST-ENT-002',
                        'name' => 'Draffin Bipod Rods',
                        'quantity' => 1,
                        'sort_order' => 2,
                        'remarks' => 'Mouth gag support',
                    ],
                    [
                        'code' => 'INST-ENT-003',
                        'name' => 'Tonsil Dissector and Pillar Retractor',
                        'quantity' => 2,
                        'sort_order' => 3,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-ENT-004',
                        'name' => 'Tonsil Holding Forceps',
                        'quantity' => 2,
                        'sort_order' => 4,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-ENT-005',
                        'name' => 'Eve Tonsil Snare',
                        'quantity' => 1,
                        'sort_order' => 5,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-ENT-006',
                        'name' => 'Adenoid Curette, Medium',
                        'quantity' => 1,
                        'sort_order' => 6,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-ENT-007',
                        'name' => 'Magill Forceps, Adult',
                        'quantity' => 1,
                        'sort_order' => 7,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-ENT-008',
                        'name' => 'Negus Artery Forceps',
                        'quantity' => 4,
                        'sort_order' => 8,
                        'remarks' => 'ENT hemostat',
                    ],
                    [
                        'code' => null,
                        'name' => 'Yankauer Suction Tube',
                        'quantity' => 1,
                        'sort_order' => 9,
                        'remarks' => 'Reusable metal suction tip',
                    ],
                ],
            ],
            [
                'set_code' => 'SET-OPHTH-CATARACT-01',
                'set_name' => 'Ophthalmology Cataract Instrument Set',
                'description' => 'Used for cataract surgery support, anterior segment access, and intraocular lens handling.',
                'is_active' => true,
                'instruments' => [
                    [
                        'code' => 'INST-CAT-001',
                        'name' => 'Castroviejo Needle Holder, Straight',
                        'quantity' => 1,
                        'sort_order' => 1,
                        'remarks' => 'Fine ophthalmic needle holder',
                    ],
                    [
                        'code' => 'INST-CAT-002',
                        'name' => 'Colibri Forceps, 1x2 Teeth',
                        'quantity' => 1,
                        'sort_order' => 2,
                        'remarks' => 'Corneal fixation',
                    ],
                    [
                        'code' => 'INST-CAT-003',
                        'name' => 'McPherson Tying Forceps',
                        'quantity' => 2,
                        'sort_order' => 3,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-CAT-004',
                        'name' => 'Westcott Scissors, Curved',
                        'quantity' => 1,
                        'sort_order' => 4,
                        'remarks' => 'Fine conjunctival scissors',
                    ],
                    [
                        'code' => 'INST-CAT-005',
                        'name' => 'Vannas Scissors',
                        'quantity' => 1,
                        'sort_order' => 5,
                        'remarks' => 'Microsurgical scissors',
                    ],
                    [
                        'code' => 'INST-CAT-006',
                        'name' => 'Barraquer Wire Speculum',
                        'quantity' => 1,
                        'sort_order' => 6,
                        'remarks' => 'Adult size',
                    ],
                    [
                        'code' => 'INST-CAT-007',
                        'name' => 'IOL Manipulator Hook',
                        'quantity' => 1,
                        'sort_order' => 7,
                        'remarks' => 'For intraocular lens positioning',
                    ],
                    [
                        'code' => 'INST-CAT-008',
                        'name' => 'Sinskey Hook',
                        'quantity' => 1,
                        'sort_order' => 8,
                        'remarks' => null,
                    ],
                    [
                        'code' => 'INST-CAT-009',
                        'name' => 'Lens Holding Forceps',
                        'quantity' => 1,
                        'sort_order' => 9,
                        'remarks' => null,
                    ],
                    [
                        'code' => null,
                        'name' => 'Lacrimal Cannula',
                        'quantity' => 1,
                        'sort_order' => 10,
                        'remarks' => 'Reusable cannula',
                    ],
                ],
            ],
        ];

        foreach ($instrumentSets as $setData) {
            $instruments = $setData['instruments'] ?? [];
            unset($setData['instruments']);
            
            $set = InstrumentSet::query()->firstOrCreate(['set_code' => $setData['set_code']], $setData);
            
            foreach ($instruments as $instrumentData) {
                // 1. Ensure the product exists
                $refNum = $instrumentData['code'] ?? ('INST-AUTO-' . strtoupper(substr(md5($instrumentData['name']), 0, 6)));
                
                $product = Product::query()->firstOrCreate(
                    ['ref_num' => $refNum],
                    [
                        'product_name' => $instrumentData['name'],
                        'product_type' => 'instrument',
                        'category' => 'Instrument Set Component',
                        'uom' => 'pcs',
                        'requires_expiry' => false,
                        'requires_lot' => false,
                        'is_active' => true,
                    ]
                );

                // 2. Link it in instrument_set_items
                \Illuminate\Support\Facades\DB::table('instrument_set_items')->updateOrInsert(
                    [
                        'instrument_set_id' => $set->id,
                        'product_id' => $product->id,
                    ],
                    [
                        'quantity' => $instrumentData['quantity'] ?? 1,
                        'sort_order' => $instrumentData['sort_order'] ?? 0,
                        'remarks' => $instrumentData['remarks'] ?? null,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                );
            }
        }
    }
}
